//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProduct", ReplyAction="http://tempuri.org/IProductService/GetProductResponse")]
        DesktopApplication.ProductService.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProduct", ReplyAction="http://tempuri.org/IProductService/GetProductResponse")]
        System.Threading.Tasks.Task<DesktopApplication.ProductService.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllProducts", ReplyAction="http://tempuri.org/IProductService/GetAllProductsResponse")]
        DesktopApplication.ProductService.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllProducts", ReplyAction="http://tempuri.org/IProductService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<DesktopApplication.ProductService.Product[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProduct", ReplyAction="http://tempuri.org/IProductService/InsertProductResponse")]
        bool InsertProduct(DesktopApplication.ProductService.Product productToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProduct", ReplyAction="http://tempuri.org/IProductService/InsertProductResponse")]
        System.Threading.Tasks.Task<bool> InsertProductAsync(DesktopApplication.ProductService.Product productToInsert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllSizes", ReplyAction="http://tempuri.org/IProductService/GetAllSizesResponse")]
        string[] GetAllSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllSizes", ReplyAction="http://tempuri.org/IProductService/GetAllSizesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllSizesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllColors", ReplyAction="http://tempuri.org/IProductService/GetAllColorsResponse")]
        string[] GetAllColors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllColors", ReplyAction="http://tempuri.org/IProductService/GetAllColorsResponse")]
        System.Threading.Tasks.Task<string[]> GetAllColorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllCategories", ReplyAction="http://tempuri.org/IProductService/GetAllCategoriesResponse")]
        string[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllCategories", ReplyAction="http://tempuri.org/IProductService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProductVersion", ReplyAction="http://tempuri.org/IProductService/InsertProductVersionResponse")]
        bool InsertProductVersion(DesktopApplication.ProductService.ProductVersion prodVerToInsert, int styleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProductVersion", ReplyAction="http://tempuri.org/IProductService/InsertProductVersionResponse")]
        System.Threading.Tasks.Task<bool> InsertProductVersionAsync(DesktopApplication.ProductService.ProductVersion prodVerToInsert, int styleNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProductCategoryRelation", ReplyAction="http://tempuri.org/IProductService/InsertProductCategoryRelationResponse")]
        bool InsertProductCategoryRelation(int styleNumber, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProductCategoryRelation", ReplyAction="http://tempuri.org/IProductService/InsertProductCategoryRelationResponse")]
        System.Threading.Tasks.Task<bool> InsertProductCategoryRelationAsync(int styleNumber, string category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : Test.ProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<Test.ProductService.IProductService>, Test.ProductService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DesktopApplication.ProductService.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<DesktopApplication.ProductService.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public DesktopApplication.ProductService.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<DesktopApplication.ProductService.Product[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public bool InsertProduct(DesktopApplication.ProductService.Product productToInsert) {
            return base.Channel.InsertProduct(productToInsert);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProductAsync(DesktopApplication.ProductService.Product productToInsert) {
            return base.Channel.InsertProductAsync(productToInsert);
        }
        
        public string[] GetAllSizes() {
            return base.Channel.GetAllSizes();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllSizesAsync() {
            return base.Channel.GetAllSizesAsync();
        }
        
        public string[] GetAllColors() {
            return base.Channel.GetAllColors();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllColorsAsync() {
            return base.Channel.GetAllColorsAsync();
        }
        
        public string[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public bool InsertProductVersion(DesktopApplication.ProductService.ProductVersion prodVerToInsert, int styleNumber) {
            return base.Channel.InsertProductVersion(prodVerToInsert, styleNumber);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProductVersionAsync(DesktopApplication.ProductService.ProductVersion prodVerToInsert, int styleNumber) {
            return base.Channel.InsertProductVersionAsync(prodVerToInsert, styleNumber);
        }
        
        public bool InsertProductCategoryRelation(int styleNumber, string category) {
            return base.Channel.InsertProductCategoryRelation(styleNumber, category);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProductCategoryRelationAsync(int styleNumber, string category) {
            return base.Channel.InsertProductCategoryRelationAsync(styleNumber, category);
        }
    }
}
